
language: python
python:
    - "2.7"
    - "3.6"
#command to install dependencies
install:
    - pip install -e .[test]
#command to run tests
script: py.test --cov=. --cov-report term-missing

notifications:
  email: false

env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true